name: Build

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5,10,15,20 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install armadillin
    - name: Do everything
      run: |
        wget https://data.nextstrain.org/files/ncov/open/aligned.fasta.xz
        armadillin --seqs_are_aligned aligned.fasta.xz > assignments.tsv
        rm aligned.fasta.xz
        gzip --force assignments.tsv
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
